### ISSUE TITLE
Enable acceptance "robot" tests for the add-on

### ISSUE THREAD

**Issue by datakurre** [collective/collective.ifttt#1]
@Shriyanshagro 

At first, try to run locally

```
bin/test --all
```

That should run all integration test plus some acceptance robot test that will try to open Firefox and run a Selenium test on it.

That requires this binary extracted from https://github.com/mozilla/geckodriver/releases to be on your PATH while running the command.

If that does not work, ping me at Slack.

Once it works for you, enable it also at Travis with replacing ``bin/test`` with ``bin/test --all``.

Do that in a new branch, so we only merge the change once also Travis passes.

**Comment by Shriyanshagro** [comment]
@datakurre I'm not follow up with binaries. Please elaborate, also, which version should of it should I go with?

**Comment by datakurre** [comment]
Because this was not done in a branch, we have not broken build at master branch.

It's not good to learn to fix it using a branch, so I created a new ticket https://github.com/collective/collective.ifttt/issues/4
