### ISSUE TITLE
Documentation for enabling RSS feeds on Plone

### ISSUE THREAD

**Issue by Shriyanshagro** [collective/collective.ifttt#11]
An easy to understand cookbook for non-IT folks.
This will include - 
- [x] Click these buttons/tabs
- [x] related screenshots

**Comment by Shriyanshagro** [comment]
Current verison of sphinx documentation is [here ](http://collectiveifttt.readthedocs.io/en/sphinx/).

**Comment by tkimnguyen** [comment]
Testing Slack / GitHub integration...

**Comment by Shriyanshagro** [comment]
Follow up on #21
