### ISSUE TITLE
Story 5 : Continuously Deployed Demo Site : 8 Points

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#20]
As an integrator, I can see the add-on in action on an example demo site, so that I can see the advertised features working.

(Requires Nejc Zupanc (“zupo”) for sponsored paid plan for the period of GSOC.)

Tasks:
- [x] Heroku-Plone-buildpack -based integration like in Heroku-Plone-button (see plone.org/download for an example)
- [ ] A deploy button on README so that anyone can create their own demo site
- [x] Creation of Heroku site from the repository
- [x] Configuration of Heroku site to be updated from each commit

**Comment by Shriyanshagro** [comment]
In continuation of #6

**Comment by datakurre** [comment]
@zupo Has created a demo site today at https://collective-ifttt.herokuapp.com/Plone

Thanks.

Maybe he could pass admin credentials to @tkimnguyen and @skleinfeldt so they can now start using the demo site to try out and review the add-on as soon as new features get merged to master.

I'd say we drop the task for "Deploy button" for now to limit this issue only for the current GSOC review site. We may re-think about it later.

**Comment by skleinfeldt** [comment]
Thank you @zupo !!!

@datakurre I agree about the deploy button, I moved it out of the task list and added it to our list of possible future stories in the Google doc. Moving this story to Done!
