### ISSUE TITLE
Story 6 : IFTTT RSS Feed : 3 Points

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#21]
As an admin, I can enable an RSS feed for any collection on my site, so that  IFTTT can use it as a trigger. 

No coding required for this story, instead create step by step documentation for a non-developer site admin to follow. Including screenshots would be great.

Tasks:
- [x] Create cookbook documentation in Sphinx for enabling RSS feeds generally on a Plone site, and specifically for a particular collection
- [x] Include an explanation of what the RSS URL for the collection is
- [x] Find a willing partner to use the docs to create an RSS feed for a collection on their site - this will test the documentation and create a feed we can use for story 7 (Sally)

**Comment by skleinfeldt** [comment]
Partners:
- Jeff Bowman of http://mountaineers.org
- Lain Wilson of http://doaks.org

**Comment by Shriyanshagro** [comment]
cookbook follow up at #11

**Comment by skleinfeldt** [comment]
Feedback:

Is there a configuration problem?
- This link in the collective.ifttt Readme doesn't work right: http://collectiveifttt.readthedocs.io/en/latest/
- This link is where I can see the documentation: http://collectiveifttt.readthedocs.io/en/sphinx/

"Welcome to collective.ifttt’s Tutorial!" seems unnecessary, just adds an extra indentation level.

"If you want to aggregate content from all the site to RSS feed" -> "If you want to aggregate a particular set of content to an RSS feed" (Aggregating all content is just one example of what can be done.)

"Below are the steps to enable RSS Feed on Plone Site." -> Move to a new paragraph after the end of this paragraph.

"You can choose what content types ends up to the RSS stream." -> That's not the only thing you can choose - labels, dates, location on the site, all the usual things you can do with collections. 

"the aggregator is language aware" -> By aggregator do you mean the collection? Better not to introduce new terms if you don't need to. (We're going for a low common denominator.)

After this comes the "Below are the steps to enable an RSS Feed..." paragraph. Here you should make it clear that you are going to give, as an example, creating an RSS feed for all the content on the site, but that it's possible to make lots of different kinds of RSS feeds given the flexibility of collections.

I think you could skip the "Prerequisite" - it goes without saying that you need to be able to create a collection. And it also goes without saying that you'll need Admin role to go to Site Setup (next comment).

Before diving into creating the example collection, you should explain how to enable RSS feeds on the Plone site. (I don't think they are enabled by default, or even if they are, the admin should check to make sure.) On Site Setup/Syndication.

Giving the collection an initial name and then renaming it later adds an unnecessary step, just give it the name you want to start with, "Site Feed". 

"On Settings tab, choose Exclude from navigation" -> Explain why you want to do this.

"Choose content types criteria (Choose Title , to publish all content)" -> Aren't you choosing the collection's criteria? And I found the choice of Title containing blank confusing. Wouldn't it be more logical to use workflow state = published?

Agree with Kim that Effective Date is a better sort criterion than Creation Date.

"You can now preview the content of RSS feed on View tab." -> The view tab shows you what the collection looks like, not the RSS feed, which looks different as far as I remember. I think the path to the RSS feed is something like /path/to/collection/rss, you should explain this.

 "You can now test RSS feed by copy-pasting RSS URL from the site action to your RSS Reader, like Google Reader." -> Can all RSS readers deal with the collection URL instead of the RSS URL? I may be behind the times on this! In which case my previous comment may be moot.

**Comment by skleinfeldt** [comment]
The Plone 5 documentation on the syndication control panel is pretty useless: https://docs.plone.org/adapt-and-extend/config/syndication.html.

This page gives an explanation of the syndication edit tab for Plone 4 (probably the same on P5?) https://www2.le.ac.uk/webcentre/plone/build/advanced/creating-an-rss-feed-from-plone-content-syndication

@datakurre and @tkimnguyen please post your advice here on how to properly configure the syndication control panel and the syndication tab on the collection, to achieve what we are after for this story.

**Comment by tkimnguyen** [comment]
after playing with syndication-controlpanel it seems minimally you need to check “Allowed” and “Show settings button” for the Syndication button to appear in the toolbar for a particular folder. “Enabled by default” does not seem necessary

**Comment by tkimnguyen** [comment]
On the synPropertiesForm for a given folder, the "Enabled" box needs to be checked (it won't be checked initially unless the "Enabled by default" box is checked on the syndication-controlpanel). The "Render Body" box can probably be left unchecked (the only times I've checked it is when I wanted the entire body of the content item to show up on, say, planet.Plone.org); the body of the content item is probably not necessary for IFTTT actions

**Comment by Shriyanshagro** [comment]
@skleinfeldt @tkimnguyen @datakurre 
All the suggested changes have been incorporated.

**Comment by skleinfeldt** [comment]
Greatly improved. 2 problems remain:

Screenshots in the Adding Collection section don't show syndication tab on edit bar until step 6 when it suddenly appears. Shouldn't it be there after adjusting the syndication control panel settings? It would be worth mentioning in the documentation of the control panel settings that by checking the "show settings button" you will get that tab on the edit UI.

As discussed, the short name field does not always show on the Settings edit tab. Better to skip this step of changing the short name.

**Comment by tkimnguyen** [comment]
The issue was auto-closed when I merged the PR

**Comment by tkimnguyen** [comment]
@Shriyanshagro I did not delete your 'sphinx' branch after merging, so you can push more changes to it

**Comment by skleinfeldt** [comment]
A couple of additional feedback points. @tkimnguyen tell me if I'm being too picky.

None of the screenshots for creating collections until step 5 show Syndication on edit bar, including on site root. But by enabling it on the control panel, it should show, right?

Screenshots for the add collection (step 3 and 4) are inconsistent, one shows blank edit tab the other doesn't.

Step 5 after publishing the collection deserves a separate step explaining how you can view the RSS feed of your collection at the special URL. Then the next step, showing the feed icon makes more sense as a way to make that URL visible. 

Step 6 showing feed icons - can't they show on both folders and collections? In which case I think it would be better to continue with the collection you just created as the example. Also the 2 screenshots together is confusing, if you continue with the collection example you don't need the top one.

"To publish feed of a particular folder" -> using the word publish here might confuse people with the publishing action, better to say "To view the feed of a particular folder or collection"...

**Comment by skleinfeldt** [comment]
Following up on the above: the site root is not a normal folder so in fact won't show the syndication tab (which shows on folders and collections). So never mind about new screenshot for this but explain why the syndication tab doesn't show there.

Also one more comment and really the most important one: RSS feeds from Plone can be used on IFTTT without doing anything special. (No secret key, no IFTTT trigger needed.) This should be at the very beginning of the page. Plone can create an RSS feed from any collection or folder, you just need to know how to enable it. Because you don't need to configure your secret key to do this I think this should be the first topic. The second topic should be story 7, creating an applet from a Plone RSS feed. Then the third topic can be configuring the secret key, which is the first step in creating custom IFTTT triggers.

**Comment by Shriyanshagro** [comment]
@skleinfeldt Can we close this issue now? And move the ticket to `Done` in projects?

**Comment by tkimnguyen** [comment]
@skleinfeldt I'm not sure if your question to me above was specific to the absence of the Syndication toolbar button at the root of the site or if you were referring to all the points in that comment.

I took a quick read of what's currently at http://collectiveifttt.readthedocs.io/en/latest/Enable_RSS_feed_on_Plone.html and it looks pretty good. 

Some suggestions:
- In the introduction, you say "you first create a collection content item", but the next section, "Enabling RSS Feed" says that the first step is to enable RSS feeds. Might need to synchronize those two things.
- I would change "Enabling RSS Feed" to "Enabling RSS Feeds on Your Site" or "Enabling Syndication" to distinguish between enabling the feed on one particular folder or collection and enabling syndication (feeds of any kind) generally for the site
- Further below where you write "Like in my case the URL to the RSS feed is- http://localhost:8080/Plone/plone-site-rss-feed/RSS which is something like /path_to_parent_collection/collection_short-name/RSS" I think that last path should be "/path_to_parent_folder/collection_short-name/RSS"
- In the next step 6, "To show feed icons on Folders" instead of the word "icons" maybe use "links". You do this elsewhere on this page.

**Comment by skleinfeldt** [comment]
@tkimnguyen I meant everything, not just Syndication. And speaking of being picky, I just did my picky picky wordsmithing on this documentation. (Changes merged to master.) I fixed all the points you raised in the process.

@Shriyanshagro there is one more change I need you to make and then this is good to close. Please replace Enable_Rss_Feed/creating_collection/Step4.png - the first image for adding a collection - with a screenshot that shows the Add Collection screen. It should look like Enable_Rss_Feed/creating_collection/settings_tab.png but on the default tab. The current screenshot shows editing a collection, not creating it.

**Comment by skleinfeldt** [comment]
@Shriyanshagro I can make a separate ticket for the above change if it would be helpful.

**Comment by Shriyanshagro** [comment]
@skleinfeldt image is updated

**Comment by skleinfeldt** [comment]
Yay! Closing!
