### ISSUE TITLE
Story 8 : Configure IFTTT : 8 Points

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#23]
As an admin I can configure my IFTTT secret key in a Site Setup control panel, so that I can later create IFTTT Triggers on my site.

Tasks:
- [x] Sign up for an IFTTT account and get your secret key
- [x] Define settings interface (schema) with BytesLine attribute for the key
- [x] Create form for the control panel by following the tutorial
- [x] Register configlet for add-on specific control panel to show it on the control panel
- [x] Write test to check for existence of control panel
- [x] Write user documentation, a new Sphinx page "Configuring Your IFTTT Secret Key" (include briefly how IFTTT triggers work, why you need a key, how to get your key, how to use the control panel to configure Plone with it)
- [x] Create upgrade step to upgrade existing add-on installation to include the control panel (without uninstall and install) (this makes this 8 points instead of 5)

**Comment by datakurre** [comment]
@Shriyanshagro Minor notes https://github.com/collective/collective.ifttt/commit/8e81db2d54c147257dd41f1d1bc8c1793432b6cb

**Comment by skleinfeldt** [comment]
Documentation feedback:

Add the concept that IFTTT applets consist of triggers and actions. (The web services you mention can provide both triggers and actions.)

Add an explanation at the end of the first paragraph explaining how collective.ifttt enables any Plone site to play in the IFTTT ecosystem by allowing you to create IFTTT triggers, and to do that you need to configure the site with your secret key.

If the screen shots show your actual IFTTT secret key, you should obscure most of it, you don't want to publish that!

**Comment by Shriyanshagro** [comment]
@skleinfeldt That secret key in the screenshot is some random string taken from IFTTT documentation.
Also, documentation is updated as per suggestions

**Comment by skleinfeldt** [comment]
Looks good, minor minor edit: "Copy this key to Plone’s IFTTT Settings." -> "Copy this key to Plone’s IFTTT Settings and click Save."

The docs on the add-controlpanel branch seem out of date, don't know if this is a problem @Shriyanshagro.

Documentation on this story is now done as far as I'm concerned. (When everything is on master I'll make a few extra tweaks.) @tkimnguyen please move story to Done and close this when you are satisfied the functionality and tests are complete.

**Comment by Shriyanshagro** [comment]
@datakurre @skleinfeldt Can we close this issue now? And move the ticket to `Done` in projects?

**Comment by skleinfeldt** [comment]
@Shriyanshagro @tkimnguyen @datakurre I have done my picky wordsmithing on the documentation for this story. 

I have one change to request on this story. @Shriyanshagro please
- Change the name of the control panel to "IFTTT Settings" (instead of "Ifttt Settings")
- Change the help text on the Secret Key field to "Register an IFTTT secret key"
- Replace the Site Setup and control panel screenshots to new ones showing the above

I can make a separate ticket for this if it would be helpful.

@datakurre and @tkimnguyen have you tested this story and do you consider it done?

**Comment by datakurre** [comment]
@skleinfeldt This is the story for which I wrote an example acceptance test, so besides wording changes this was been done for a week.

https://github.com/collective/collective.ifttt/blob/master/src/collective/ifttt/tests/robot/test_controlpanel.robot

**Comment by Shriyanshagro** [comment]
@skleinfeldt your suggestions on documentation have been incorporated.

**Comment by skleinfeldt** [comment]
@Shriyanshagro I don't see screenshots with the fixed IFTTT spelling ("IFTTT Settings" instead of "Ifttt Settings"; "Register an IFTTT secret key" instead of "Register an Ifttt secret key").

Please use IFTTT rather than Ifttt wherever it shows to users (in UIs and documentation). Your new documentation section for story 9 "Trigger Ifttt Action" has the same problem.

**Comment by Shriyanshagro** [comment]
@skleinfeldt you can view it [here](https://collectiveifttt.readthedocs.io/en/story-8-configure-ifttt/Configuring_Your_IFTTT_Secret_Key.html).
I suggest you clear your browser cookies before viewing.

**Comment by Shriyanshagro** [comment]
Also, I'll update ifttt/Ifttt > IFTTT in other documentations

**Comment by skleinfeldt** [comment]
@Shriyanshagro ooops sorry! Didn't realize I needed to review on the branch. Looks good!

When this is merged and the docs are live we can close this.

**Comment by Shriyanshagro** [comment]
@skleinfeldt I believe we can close this. The changes (ifttt>>IFTTT) have to be incorporated in story 9.

**Comment by skleinfeldt** [comment]
Everything looks good on the branch. I'll close this when the PR is merged and the new docs are live at http://collectiveifttt.readthedocs.io/en/latest/index.html

**Comment by datakurre** [comment]
@skleinfeldt Would you merge documentation related requests if I merge all code and test related ones?

**Comment by skleinfeldt** [comment]
@datakurre I have never merged a PR, I'll do it if you tell me how. I'm also fine with you doing it if that would be faster.

**Comment by datakurre** [comment]
@skleinfeldt Please try. It would be nice, because I don't know when those are ready. And UI for merging PR was the feature that made GitHub the thing.

At the end for the each pull request there is a big green button "Merge pull reguest":

* https://github.com/collective/collective.ifttt/pull/39
* https://github.com/collective/collective.ifttt/pull/37

If it is not green, it should not be pushed. If it's green, just push and click through the questions until it's done:

* If it asks for a merge strategy, "Create a merge commit" is fine
* Default commit message is usually fine.

After merging the branch it is usually ok also to delete the merged branch from the suggested button (if available), but leaving those behind do not matter. GitHub branches view also makes it easy to clean up all the old branches when needed.

**Comment by Shriyanshagro** [comment]
Nice job Sally, you did all right 👍 😀

**Comment by skleinfeldt** [comment]
Checked http://collectiveifttt.readthedocs.io/en/latest and updated docs are live! Closing and moving to Done.
