### ISSUE TITLE
Story 9 : Content Rule Action : 13 Points

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#24]
As an admin I can create a content rule and use "Trigger IFTTT" as an action, so that I can integrate content rules with IFTTT. 

I can configure
- The IFTTT event name
- Whether the 3rd IFTTT payload is Description, Username of editor, or Event Start Date/time of the content item

The 1st IFTTT payload will be Title, and the 2nd payload will be the URL of the content item.

Tasks:

- [x] add config file to add IftttTriggerAction
- [x] add schema to input ifttt_event_name
- [x] add schema to choose 2nd payload
- [x] add schema to input for choosen payload
- [x] acceptance tests
- [x] unit tests
- [x] write documentation

**Comment by skleinfeldt** [comment]
To be discussed: whether to have 1 content rule action with configurable 3rd payload (Description, Username of editor, or Event Start Date/time), or 3 separate content rule actions one for each possible 3rd payload.

Note that this content rule action(s) is intended for use under the hood by the higher-level add-on functionality (like story 10, Content Trigger), or by more advanced integrators who want to combine it with other stuff. So usability is not really an issue here. The driving concern should be what is the best implementation to build from.

**Comment by skleinfeldt** [comment]
@Shriyanshagro always do a task breakdown before starting to work on a story, so we know your plan of action. To do that, edit the first comment and put a checklist of tasks under the "Tasks" heading. Earlier stories have had the task list done by others, now we'd like you to start doing them.

**Comment by Shriyanshagro** [comment]
@tkimnguyen @skleinfeldt @datakurre 

I have a doubt. Are we keeping `description` as optional payload or mandatory? In case, 
if it's optional then,
 we only ask `ifttt_name` and `optional payload`
else,
 `ifttt_name`, `description` and `optional payload`

From our last conversation, I remember we were keeping it optional?

**Comment by skleinfeldt** [comment]
@Shriyanshagro Description is one of the 3 possible choices for the 3rd payload, the other choices are Username of the editor, or Event Start Date of the content item. The 3rd payload is mandatory, not optional, one of those 3 things must be selected by the admin when creating the content rule. (Although if they choose Event Start Date and then inadvertently use the rule on non-event content your code should not fail but simply skip the 3rd payload.) 

Title is the mandatory 1st payload and URL is the mandatory 2nd payload. Apologies, I made a typo when writing the story by saying Description was the 2nd payload! Which obviously was confusing. I fixed that and the story is now correct.

**Comment by datakurre** [comment]
@skleinfeldt Was ”username of editor” supposed to be username of the user triggering the event or username saved as creator of the content?

**Comment by skleinfeldt** [comment]
@datakurre @Shriyanshagro Username of the user triggering the event. Use cases would be keeping track of who is changing content on a site - by piping the information to a Slack channel or a Google spreadsheet.

**Comment by Shriyanshagro** [comment]
@skleinfeldt you can start reviewing documentation related to this story
https://collectiveifttt.readthedocs.io/en/story-9-content-rule-action/

**Comment by Shriyanshagro** [comment]
@skleinfeldt ifttt/Ifttt is now changed to IFTTT for  UI/Documentation on story9

**Comment by skleinfeldt** [comment]
@Shriyanshagro help! The documentation for this story is no longer shown at https://collectiveifttt.readthedocs.io/en/story-9-content-rule-action/ Where did it go?

**Comment by skleinfeldt** [comment]
I'm reviewing by looking at the RST file on the branch, hopefully that's right: https://github.com/collective/collective.ifttt/blob/story-9-content-rule-action/docs/Trigger_Ifttt_Action.rst

**Comment by skleinfeldt** [comment]
@Shriyanshagro and fyi @tkimnguyen 

First, some comments about doing some high level doc restructuring to bring this in line with where collective.ifttt is headed.

When you wrote this, I think you were still confused about the difference between story 9 (creating a new content rule **action**) and story 10 (creating the "Content Trigger" feature on the edit toolbar's Action menu, which uses that content rule action under the hood). The non-technical site admins that we are primarily targeting with this add-on will be interested in story 10. Story 9 is something only the more technical admins will care about. With that in mind, the structure of the documentation should be something like:
- What Is IFTTT? - the "Introduction" section of docs/index.rst should be moved here (and remove the "Introduction" and "Contents" headers in index.rst)
- Introduction to IFTTT Applets - empty placeholder for a _brief_ explanation of what IFTTT applets are, and how you can create them, link to the IFTTT video tutorial, https://www.youtube.com/watch?v=4khyxYekPFQ
- Enabling RSS Feeds on Plone Sites - this is done
- Using Plone RSS Feeds in IFTTT Applets - empty placeholder for story 7
- Configuring a Plone Site with an IFTTT Secret Key - this is done
- Creating an IFTTT Content Trigger - empty placeholder for story 10 (no need to screenshot the Actions menu where this will be launched because that will change!)
- Creating an IFTTT Content and User Trigger - empty placeholder for story 11
- Creating an IFTTT Event Trigger - empty placeholder for story 12
- [Editing and Deleting Existing IFTTT Triggers - haven't written this story yet]
- [additional stories/features we decide to add]
- Advanced: The "IFTTT Trigger" Content Rule Action - this is the section we're working on for this story (Trigger_Ifttt_Action.rst)

With that in mind, you need to rewrite this doc to make it clear that:
- Content rules are a powerful Plone feature that... - one sentence description and link to Plone docs on content rules
- Content rules consist of conditions and actions, and what that means
- Collective.ifttt contains a new content rule action, _Trigger IFTTT_, that posts an event to the IFTTT web service when a content rule's conditions are satisfied
- Content rules with the _Trigger IFTTT_ action are used to implement the IFTTT triggers that collective.ifttt provides (Content Trigger, Event Trigger, etc.)
- You can create your own custom IFTTT trigger event by combining the _Trigger IFTTT_ content rule action with your own conditions
- Then follows the example of how to create a content rule that that will send an IFTTT trigger any time News Items are modified.

Other suggestions
- A lot of the text on this page is currently misleading because of your initial confusion, you need to rewrite a bunch of things with your better understanding
- For example, never say "IFTTT action" on this page (that refers to the "then that" actions IFTTT performs) - here we're talking about a Plone content rule action that is used to create an IFTTT trigger 
- You are going to have to be really careful to differentiate between **content rule triggers, conditions, and actions** and **IFTTT triggers and actions**
- This content rule action should be called "IFTTT Trigger" not "IFTTT Trigger Action" (goes without saying it is an action since it will be on the actions menu)
- You don't need to repeat the things that are documented at https://docs.plone.org/working-with-content/managing-content/contentrules.html (like the lists of triggers and actions and all the things you copy/pasted from there)
- Instead you can say something like "Following the instructions given on the Plone documentation [link]" create a content rule as follows and assign it to a folder on your site (or at the site root)
  - Triggering event: Object modified
  - Condition: Content type equals News Item
  - Action: IFTTT Trigger
- Definitely show the screenshot for configuring the action - the other screenshots and blow by blow descriptions are nice but not necessary (especially when they duplicate Plone documentation)

**Comment by Shriyanshagro** [comment]
@skleinfeldt yes, you were right. Also, documentation is updated. 
Seems like fixing IFTTT naming conventions was not an easy task

**Comment by skleinfeldt** [comment]
@Shriyanshagro Here's feedback on the new index.rst that I am seeing on the story-9-content-rule-action branch. It should say a little something. Start with the first sentence of the Readme file. Then put in the paragraph before the contents of the old index.rst ("This documentation will teach you how...")

**Comment by skleinfeldt** [comment]
@Shriyanshagro Also quick feedback on Trigger_IFTTT_Action.rst. I haven't read most of it yet, but change the title to **Trigger IFTTT" Content Rule Action**.

**Comment by Shriyanshagro** [comment]
@skleinfeldt are there any more suggestion coming on this story for docs?  If not, then I would start incorporating the suggested changes.

**Comment by skleinfeldt** [comment]
@Shriyanshagro on Trigger_IFTTT_Action.rst and on the content rule action UI there is a mistake.

> For the “IFTTT applet name” enter: the IFTTT applet which you want to trigger.

This should say "IFTTT event name" not applet name. Multiple applets can use one event, we are defining an event here.

The section "Working example of IFTTT Trigger" might ultimately be moved to a fuller example that shows setting up the IFTTT applet and showing the resulting email or Google spreadsheet entry. It seems a little incomplete here.

Other than that, looks OK - much better than before.

**Comment by Shriyanshagro** [comment]
@skleinfeldt @datakurre suggestions on this story are added.
I will update the section "Working example of IFTTT Trigger" with story 7.

**Comment by skleinfeldt** [comment]
@Shriyanshagro  Addendum to my comment above about a "fuller example". Writing to a spreadsheet would be a great example for story 7, the RSS feed applet, but that example is a separate discussion. RSS applets are different from applets based on custom trigger events like from stories 9, 10, 11, 12. What I meant to suggest is that the example that you wrote for story 9 should maybe be a separate page that could also apply to stories 10, 11, 12. Although come to think of it each of those stories implies a different IFTTT use case, so maybe should have different examples. The story 10 example should post to Facebook or Twitter, the story 12 example should create a google calendar event, and the story 11 example should post to a Slack channel. The story 9 example could do anything.

So, having thought about it more I agree that we should discuss this further and decide what to do later, when those stories are done.

**Comment by skleinfeldt** [comment]
@Shriyanshagro I moved the story 9 documentation page to the bottom of the TOC since this is an advanced feature that is optional to use.

**Comment by skleinfeldt** [comment]
Deployed and done!

**Comment by skleinfeldt** [comment]
On second thought - before we close this we need @tkimnguyen to test

**Comment by skleinfeldt** [comment]
Closing for the team.
