### ISSUE TITLE
Story 10 : Content Trigger : 13 Points

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#25]
#47 As an admin I can add an IFTTT "Content Trigger" to any folder on my site that will send a trigger to IFTTT when content at or below the current path is published. This will allow me to create IFTTT applets to, for example, email, tweet, or Facebook post about the content.

I can configure
- The IFTTT event name
- The content types to restrict to
- The workflow transitions to restrict to

The trigger will include 3 payloads for the content item
- Title
- URL (for files/images, to view)
- Description

This story provides the user with a simple form to create an IFTTT trigger. Under the hood the code will created a content rule to do the work, but the user does not know that and doesn't care. 

For this story, the feature will be added to the Actions menu ("Add IFTTT Content Trigger" or some such). We will address the question of a better UI for all the IFTTT features in a future story (or stories).

Tasks:
- [x] Play with making content rules
- [x] Custom permission: collective.ifttt: Can add content trigger
- [x] Assign permission to role Site Administrator by default (rolemap.xml)
- [x] Register an actions menu item ./profiles/default/actions.xml restricted with role and to be visible only on folders (check “available_expr” examples in Plone actions.xml)
- [x] create upgrade step
- [x] Action is a link to browser view with a form with options (schema and "Add" button)
- [x] Option to restrict certain content types (types from plone.app.vocabularies)
- [x] Option to restrict certain workflow transitions (transitions from plone.app.vocabularies)
- [x] Add new rule
- [x] Add trigger conditions to rule
- [x] Configure action to rule
- [x] Add this new content rule to the folder (at and below the current path)
- [x] Give notification to user
- [x] Write tests
- [x] Write documentation

**Comment by skleinfeldt** [comment]
This will rely on Plone's content rules machinery for implementation, but the user interface will be way, way simpler. See https://www.makeuseof.com/tag/ifttt-connect-anything-maker-channel/ for an example.

This story is restricted to implementing the simplest possible initial version of the "Content Trigger". It should be tailored to a particular set of IFTTT applet use cases (tweet/post/email about newly published content) and be very easy for site admins to set up. Subsequent stories will
- Add other types of triggers for other IFTTT use cases (for example one with a date payload for applets that add events to calendars, another with a user payload for applets that pipe site editing info to Slack or spreadsheets)
- Extend the Content Trigger or create new triggers for content additions, deletions, and other types of changes (not sure what the IFTTT use cases are for these)
- Add the ability to edit and delete existing triggers

This feature could simply be added to the normal Actions menu ("Add IFTTT Content Trigger"), but given that there will eventually be more IFTTT triggers plus functionality to edit and delete existing triggers, we should think ahead about the eventual UI for presenting all IFTTT features to admins. For example we could make a new entry on the edit bar called "IFTTT" which could work similar to the way "Add new" works - clicking "IFTTT" gives you the list of available triggers, clicking one gives you a form with Save/Cancel. Providing a UI for the ability to see the list of triggers that have already been added and allowing them to be edited or deleted, will require more thought that should probably be postponed to a later story when we have a few triggers working.

Note that content rules can only be applied to folders AFAIK, and we will follow that restriction here. There might be use cases for setting a trigger on a particular content item, so we should not do anything to eliminate that possibility. (Or if that would be impossibly difficult we can just not support it.)

**Comment by skleinfeldt** [comment]
Asko's technical notes from planning meeting:

- Custom permission: collective.ifttt: Can add content trigger
- Permission assigned to role Site Administrator by default (rolemap.xml)
- Link in action menu
- Link open form with options
  - The IFTTT event name
  - The workflow change to trigger the event (transition from plone.app.vocabularies) (this is content rule trigger event)
  - The content types to restrict to (types from reallyFriendlyContentTypes) (this is content rule condition)
  - Whether the 3rd payload is Description, Username of editor, or Event Start Date/time
- Form submission ensures that content rules are enabled configures content rule for IFTTT action

**Comment by datakurre** [comment]
@Shriyanshagro These look up to date for creating schema based forms:

https://docs.plone.org/develop/addons/schema-driven-forms/creating-a-simple-form/creating-a-schema.html

https://docs.plone.org/develop/addons/schema-driven-forms/creating-a-simple-form/creating-the-form-view.html

With, of course, an exception

OrderFormAdapter implemented and registered in that guide is not required if the form class (OrderForm) had class attribute `ignoreContext = True`.

**Comment by skleinfeldt** [comment]
@Shriyanshagro @datakurre did you have any discussion of the task list or approach? I thought the idea was to do research, task breakdown, discussion this week and implement next week?

**Comment by Shriyanshagro** [comment]
@skleinfeldt @datakurre As you can see in the tasks list, this story is already broken down into individual tasks. Now among those tasks, there are two of them which requires research as I have never dealt with them:
 1. Registering new Action `Add IFTTT Content Trigger`. Which I have already implemented during the ongoing research for it in #47
2. Dynamic Creation and configuration of the new content rule. For which I have recently started this [topic](https://community.plone.org/t/dynamic-creation-of-content-rules/6705) on the community forum to get some insights.

**Comment by Shriyanshagro** [comment]
@datakurre  @skleinfeldt For the following two tasks:
 -  Option to restrict certain content types
 -  Option to configure workflow state for trigger
There are two possibilities on UI:
 - Checkbox option: Where user can check the types which they want to either include or exclude
 - Drag and Drop option: Where they can drag certain types from left box to right box

Which is suitable here?

**Comment by Shriyanshagro** [comment]
@skleinfeldt @datakurre Queries regarding trigger:
- What should be the `title` and `description` of the added content rule? I don't follow up with "context derived name".
- What all options should be checked while adding the rule? Below is the screenshot for options:
   <img width="625" alt="screen shot 2018-06-21 at 12 05 44 am" src="https://user-images.githubusercontent.com/13868098/41677748-ddca1d18-74e6-11e8-9d26-0d7f7725d9c3.png">
- What should be the 3rd payload for IFTTT request?
     - `username`?

**Comment by datakurre** [comment]
For content type widget, Plone 5 uses Select2 elsewhere. That is available for schema widget directive as plone.app.z3cform.widget.SelectFieldWidget.

Title should be something that both describes and distincts rukes created from that action menu item. Forget ”context derived name”. That was a bad idea.

Those default options should be good.

**Comment by skleinfeldt** [comment]
@Shriyanshagro The user should be able to choose the set of workflow states that are the trigger condition, just like they can choose a set of content types.

Probably "Stop executing rules" and "Cascading rule" should be checked, but I'm not sure.

**Comment by Shriyanshagro** [comment]
@skleinfeldt I have made a few tweaks in the documentation, which I noticed while writing documentation for story 11 and story 12. 
Can you kindly re-check it [at](https://collectiveifttt.readthedocs.io/en/story-10-content-trigger/content_trigger.html)
Basically, I added a new section named `Default Settings` to it.

**Comment by skleinfeldt** [comment]
@Shriyanshagro That section seems like a good idea, but under Conditions those aren't defaults in this case, the workflow state (2.) is what you just configured.

**Comment by skleinfeldt** [comment]
@tkimnguyen Please test and close if satisfied.

**Comment by skleinfeldt** [comment]
Closing for the team.
