### ISSUE TITLE
Add Github description to repo

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#29]

**Comment by skleinfeldt** [comment]
@Shriyanshagro this is not the Readme or the Sphinx documentation, it is the brief description at the top of the Github project (where it says "No description, website, or topics provided.") No website or topic needed, just a description.

**Comment by Shriyanshagro** [comment]
I have updated it and had nothing more to add. Please feel free to add any required content to it.

**Comment by skleinfeldt** [comment]
I do mean that, it wasn't done when I opened the ticket :-)

Closing.

**Comment by Shriyanshagro** [comment]
No, I've updated it after Sally reopened this issue. Earlier I thought that intro in README.rst is sufficient.
