### ISSUE TITLE
Setting up PyCharm

### ISSUE THREAD

**Issue by datakurre** [collective/collective.ifttt#3]
At first, update your buildout with the changes in the following diff:

```diff
diff --git a/buildout.cfg b/buildout.cfg
index f191dd3..13b5eb9 100644
--- a/buildout.cfg
+++ b/buildout.cfg
@@ -13,8 +13,11 @@ parts =
     createcoverage
     releaser
     i18ndude
-    omelette
+#   omelette
     robot
+    isort
+    yapf
+    python
 develop = .
 
 
@@ -91,6 +94,25 @@ eggs = zest.releaser
 recipe = zc.recipe.egg
 eggs = i18ndude
 
+
+[isort]
+recipe = zc.recipe.egg
+eggs = isort
+
+
+[yapf]
+recipe = zc.recipe.egg
+eggs = yapf
+
+
+[python]
+recipe = zc.recipe.egg
+eggs =
+    ${robot:eggs}
+    plone.recipe.zope2instance
+interpreter = python-interpreter
+
+
 [versions]
 # Don't use a released version of collective.ifttt
 collective.ifttt =
```

* [x] disable omelette part (otherwise it confuses PyCharm)
* [x] add isort part to install ``./bin/isort`` with buildout
* [x] add yapf part to install ``./bin/yapf`` with buildout
* [x] add python part to install ``./bin/python`` interpreter with all Plone packages with buildout

Configure your project Python interpreter as new local "existing environment" with the generated ``./bin/python`` as interpreter path
![interpreter2](https://user-images.githubusercontent.com/160447/40156017-96ed3b12-599f-11e8-9962-8f0bf7c80a16.png)

This should now be enough for PyCharm to find all Plone code to allow navigation, code completion, etc... (no Buildout support -configuration needed anymore).

Then from the dropdown menu on the left from the green "play" button on PyCharm toolbar, configure task to start the Plone instance: 
![configuration](https://user-images.githubusercontent.com/160447/40156087-f9f628a4-599f-11e8-81a6-a4d8fe83d5e5.png)

This allows starting a Plone site by pressing the play button. It should also allow starting the instance in PyCharm debugger using the "bug" button next to play button.

Note: with the latest PyCharm the bug button is broken on me. With the setup above. I'm not sure if that's common issue or issue with my local setup. If the bug button does not work, you could try to also configure Buildout support. Adding that fixed the bug button for me, but broke the play button:
![buildout-support](https://user-images.githubusercontent.com/160447/40156200-9d13e6e8-59a0-11e8-93b6-2697e13bb77f.png)

Next

* [x] update setup.py with yapf configuration

```diff
diff --git a/setup.cfg b/setup.cfg
index f1aa06c..4aaa285 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -14,3 +14,15 @@ force_single_line = True
 lines_after_imports = 2
 line_length = 200
 not_skip = __init__.py
+
+[yapf]
+based_on_style = pep8
+allow_multiline_lambdas = True
+coalesce_brackets = True
+dedent_closing_brackets = True
+join_multiple_lines = False
+space_between_ending_comma_and_closing_bracket = True
+split_arguments_when_comma_terminated = True
+split_before_expression_after_opening_paren = True
+split_before_first_argument = True
+split_complex_comprehension = True
```

Then add filewatchers for yapf and isort in that order
![yapf](https://user-images.githubusercontent.com/160447/40156238-e367c6a0-59a0-11e8-8846-e01391769d73.png)
![isort](https://user-images.githubusercontent.com/160447/40156243-e639c8ec-59a0-11e8-9af4-ba2be95ceea0.png)

Now every time you save a Python file in your project, it should be reformatted with yapf + isort.

**Comment by Shriyanshagro** [comment]
@datakurre I followed all the given steps. 
But after running ./bin/buildout it throws me this error >> https://pastebin.com/sSWBhwg8

**Comment by tkimnguyen** [comment]
@Shriyanshagro to recap:
- changing buildout.cfg should not have caused the error you got 
- you can paste errors and stack traces directly here (no need for pastebin); look at the markedown styling hints at the bottom of the comment field widget or use the toolbar icons
- I suggest you start over again in a new directory and post here the steps you took to get to a working buildout in that new directory. Having those details will help me and Asko help you figure out what might have caused the buildout script to be damaged.

**Comment by datakurre** [comment]
@Shriyanshagro Please, replace line ``interpreter = python`` with ``interpreter = python-interpreter``.

Then, after you have been again able to run buildout, you can configure ``./bin/python-interpreter`` as interpreter in PyCharm and then you see all the Plone packages.
