### ISSUE TITLE
Update configuration of Sphinx Documentation

### ISSUE THREAD

**Issue by Shriyanshagro** [collective/collective.ifttt#36]
Following have to be accomplished in Sphinx documentation.

Tasks:
- [x] Change Author signature to `Plone Foundation`
- [x] Cross page navigation
- [x] Tree structure of whole documentation

**Comment by Shriyanshagro** [comment]
@skleinfeldt Here you will find the updated theme of documentation

**Comment by skleinfeldt** [comment]
@Shriyanshagro much better. But there must be a way to show all the topics all the time on the left nav? The current structure allows you to go to previous and next, but the left nav doesn't allow you to skip ahead 3 topics. It should show the overall TOC, like the Plone docs do.

**Comment by skleinfeldt** [comment]
I reviewed http://collectiveifttt.readthedocs.io/en/update-configuration-of-sphinx-documentation and hallelujah! The left nav is showing as it should. 

I'll close this when the PR is merged and the new docs are live at http://collectiveifttt.readthedocs.io/en/latest/index.html

**Comment by skleinfeldt** [comment]
It's there now, closing!
