### ISSUE TITLE
Add geckodriver for Travis-CI to fix failing build

### ISSUE THREAD

**Issue by datakurre** [collective/collective.ifttt#4]
Into ``.travis.yml`` after lines in ``-install`` add two more lines from:

```yaml
install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
- tar -xzf geckodriver-v0.20.0-linux64.tar.gz -C bin
```

Yet another tutorial for git feature branches https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow

(All this can be done also through PyCharm UI, but it might be better to learn to use git command at first and only then learn PyCharm commands.)

* [x] create new feature branch for fixing this issue
* [ ] update ``.travis.yml`` with given lines
* [ ] push to feature branch to GitHub
* [x] open pull request from the branch
* [x] wait and fix util pull request reports tests green
* [x] merge pull request
* [ ] delete obsolete feature branch (GitHub shows button after merge)

**Comment by Shriyanshagro** [comment]
@datakurre, I have followed all the suggested changes. Yet Travis builds failed.
Please look into it. #8

**Comment by datakurre** [comment]
Thanks.

Add one more like next to the previous ones

- export PATH=$(pwd)/bin:$PATH
