### ISSUE TITLE
Story 11 : Content and User Trigger : 3 Points

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#40]
As an admin I can add an IFTTT "Content and User Trigger" to any folder on my site that will send a trigger to IFTTT when content at or below the current path is edited, including the information of who changed it. This will allow me to create IFTTT applets to, for example, log the edit information to Slack or a Google spreadsheet.

I can configure
- The IFTTT event name
- The content types to restrict to

The trigger will include 3 payloads for the content item
- Title
- URL (for files/images, to view)
 - User who made the edit

Tasks:

 - [x] Implementation
 - [x] Tests
-  [x] Docs

**Comment by datakurre** [comment]
@Shriyanshagro Let's not add a workflow-state condition. I believe here the intent is that when a user with proper permission configures this rule they do want all updates. Workflow-state condition makes it more complex to understand.

**Comment by skleinfeldt** [comment]
@Shriyanshagro - I agree with @datakurre - do it as the story is written, no workflow state condition. We want to see every editing change on the site.

**Comment by Shriyanshagro** [comment]
done 👍

**Comment by Shriyanshagro** [comment]
@skleinfeldt documentation is added [here](https://collectiveifttt.readthedocs.io/en/story-11-content-and-user-trigger/user_trigger.html)

**Comment by skleinfeldt** [comment]
Docs look good. Please make the change recommended on story 10 at https://github.com/collective/collective.ifttt/issues/25#issuecomment-404168174

**Comment by skleinfeldt** [comment]
@tkimnguyen Please test and close if satisfied.

**Comment by skleinfeldt** [comment]
Closing for the team.
