### ISSUE TITLE
Story 15 : IFTTT Easyform Adapter : 13 Points

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#59]
As an admin I can add an IFTTT Adapter to a collective.easyform Form Folder. On form submit it will send a trigger to IFTTT. I can configure:
- The IFTTT event name
- Up to 3 form fields to use as the payloads

Tasks:
- [x] Implementation
- [x] Tests
- [x] Docs

**Comment by datakurre** [comment]
@Shriyanshagro You should start this by adding `collective.easyform` into buildout instance eggs list https://github.com/collective/collective.ifttt/blob/master/buildout.cfg#L33, running builldout, restarting Plone, installing Easy Form add-on from Plone site setup and following instructions to learn to use it https://collectiveeasyform.readthedocs.io/en/latest/

**Comment by datakurre** [comment]
Easy form action is made of

* configuration schema (similar to our form schemas in this project)
* action adapter, which is inherited from base Adapter and then "wrapped" with the interface (following practice in its actions.py) and finally that wrapper is registered

That action-wrapping-pattern is not generic "Plone framework design", but seems to be Easy Form custom design to avoid boilerplate (like those custom dummy form views required by content rules framework).

**Comment by skleinfeldt** [comment]
Here's a clarification of how this should work from our meeting today.

The IFTTT adapter can be added by the admin creating the form at any time. It will not be functional until it has at least 1 payload defined. So in theory the admin could add the adapter before all form fields are created, s/he could save it without any payloads defined yet, then go back and edit it to add or change the payloads.

**Comment by skleinfeldt** [comment]
Closing for the team.
