### ISSUE TITLE
Share admin access to allow mentors to configure heroku

### ISSUE THREAD

**Issue by datakurre** [collective/collective.ifttt#6]
Please, configure admin access for this repo to ”datakurre” and ”zupo” so that we can help setting up heroku integration.

**Comment by datakurre** [comment]
Thanks. I wait until I get confirmation from Nejc (zupo).

**Comment by Shriyanshagro** [comment]
@datakurre any update to this?

**Comment by datakurre** [comment]
Delayed until next week at least. This won’t block you - should be there before the first review:)

**Comment by datakurre** [comment]
https://collective-ifttt.herokuapp.com/Plone/

**Comment by datakurre** [comment]
Nejc has shared site credentials with the project members.
