### ISSUE TITLE
Weird theme issue

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#64]
When creating an IFTTT Content Trigger on the News folder, the right portlet hides part of the Workflow Transitions widget at certain scales, because the widget doesn't resize properly.

![ifttt-site-theme-bug](https://user-images.githubusercontent.com/1198463/43902697-c2cf4ef4-9bb8-11e8-9658-525c8e310bc6.png)

This is likely a bug or limitation in the widget and there's nothing that collective.ifttt can do about it. I mention it on the off-chance that @datakurre knows a way to configure the widget that makes it resize properly.

@datakurre close this if there is nothing we can do.

**Comment by datakurre** [comment]
@skleinfeldt There is nothing we can do for this issue as such, but if we used other widget (the same that is used e.g. in collection to select items for filters) this would not be an issue.

**Comment by skleinfeldt** [comment]
@datakurre thanks - as you saw on #68 I think using a simpler widget would be better, so I'll close this.
