### ISSUE TITLE
Suppress content rules info message

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#65]
When I successfully add an IFTTT Content Trigger I get a successful info message from c.ifttt, plus a misleading info message from content rules:

![ifttt-info-msgs](https://user-images.githubusercontent.com/1198463/43903116-b3f436c8-9bb9-11e8-8211-2957a3ae9805.png)

Can the content rules message be suppressed?

**Comment by Shriyanshagro** [comment]
@skleinfeldt I have mentioned this issue long back to @datakurre. But then we decided to let @tkimnguyen to take a call on it, whether we should suppress it or not?

**Comment by datakurre** [comment]
I assume that queued status messages can be cleared with

```python
from Products.statusmessages.interfaces import IStatusMessage
IStatusMessage(self.request).show()
```

**Comment by Shriyanshagro** [comment]
@datakurre this method removes all the messages, even the ones which are added after it is being called.

**Comment by datakurre** [comment]
I don’t understand how it could remove messages added after call :/

**Comment by Shriyanshagro** [comment]
Yes, I too don't understand the magic. But that's happening. 
I called it just after the creation of the content rule.  https://github.com/collective/collective.ifttt/blob/3ea56fff523eea0ede62d674340496ac661c3f8e/src/collective/ifttt/utils.py#L63

**Comment by datakurre** [comment]
I believe they are stored as an annotation on the request. You could be able to delete those manually by following https://github.com/plone/Products.statusmessages/blob/master/Products/statusmessages/adapter.py


just use IAnnotations(self.request) and the the storage key constant
