### ISSUE TITLE
Better help text on Content Rules UI

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#66]
After adding an IFTTT Content Trigger, when I look at the content rules UI I see this:

![ifttt-content-rules](https://user-images.githubusercontent.com/1198463/43903426-6ebbacb6-9bba-11e8-8d85-03d275c1fbbd.png)

It would be more informative if instead of 
> This rule is created to trigger Collective.ifttt Site News on News folder

it said

> This rule triggers an IFTTT event "Collective.ifttt Site News" on the News folder

**Comment by skleinfeldt** [comment]
Similarly on the content rules edit UI:

![ifttt-edit-content-rule](https://user-images.githubusercontent.com/1198463/43903969-9b73d390-9bbb-11e8-90cc-ead5c11aec43.png)

It would be better if instead of
> Trigger IFTTT action Collective.ifttt Site News with context title,url and description

it said
> Trigger IFTTT event "Collective.ifttt Site News" with context title, url and description

**Comment by Shriyanshagro** [comment]
@datakurre regarding validation for ifttt_event_name. Is there any better implementation this?
```  
        ifttt_event_name = schema.TextLine(
        title=_(u'IFTTT event name'),
        description=_(
            u'Give the name of IFTTT event which you want to trigger'
        ),
        required=True,
        constraints=validate_ifttt_event,
    )
```
where `validate_ifttt_event()` will check for one word constraint

**Comment by datakurre** [comment]
@Shriyanshagro This looks the correct way.

Form field validation is a bit complex subject in Plone. It has a few alternatives:

* schema field constraints is the simplest one usable here
* schema invariants can be used that that interdepending schema values are valid
* field validator is a z3c.form level concept; it is like a more complex version of schema constraint, and it also knows its context (the form, widget and everything it is registered against)
