### ISSUE TITLE
Better trigger naming convention

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#67]
The naming scheme of the content rule/IFTTT trigger is a bit obscure/geeky, whereas we are trying to be super user friendly. An IFTTT Content Trigger on the News folder is named
> News_Trigger_Collective.ifttt Site News

So that is something like `[foldername_Trigger_[eventname]`. The eventname can have spaces, so the use of underscores seems unhelpful. Another problem is that if I add another Content Trigger on the same folder, with the same event name, but on a different content type, the 2 triggers have the same name and I can't tell which is which. (Since it isn't easy to edit the trigger, the easiest way to add another content type later would be to add another trigger.)

![ifttt-trigger-names](https://user-images.githubusercontent.com/1198463/43907306-265a6918-9bc3-11e8-8741-80255db7fd7f.png)

 If the name can be normal text, how about
> IFTTT Content Trigger for "Collective.ifttt Site News" on News Items on /news
 
which is something like [ifttt-trigger-type] for "[eventname]" on [content-types] on [path]

@datakurre may have better ideas for this.

**Comment by datakurre** [comment]
@skleinfeldt Your suggestion sounds good. Obviously it requires i18n support to be translatable.
