### ISSUE TITLE
Use simpler multi-select widget on Trigger forms

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#68]
The widget used to select content types and workflow transitions on the forms to add IFTTT triggers is large (causing bad responsive behavior, see #64)  and overly complex. There is no reason for users to re-order the types/transitions they have selected, so why give them the option? A better choice would be the normal sort of multi-select widget that you get, for example, when adding a Content Type condition when editing a content rule.

**Comment by datakurre** [comment]
SelectFieldWidget from plone.app.z3cform if I remember correctly. We discussed about this before.
