### ISSUE TITLE
Add form needs validation

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#69]
If you add an IFTTT User Trigger and leave the content types blank, it creates a content rule with no conditions. (Also true for Content Trigger and for the workflow transitions field of Content Trigger and Event Trigger.) I assume this should not be allowed and the form should check for a value. 

Never mind my previous suggestion to have a blank value select all content types/transitions. Just make the field value required.

**Comment by skleinfeldt** [comment]
This problem applies to all the multi-select fields on all 3 triggers. The field is not marked required, so it is possible to submit the form with no content type or workflow transition selected. I don't think there is any reason to do that, is there? To solve the problem I think these multi-select fields should all be required.

**Comment by datakurre** [comment]
schema.List accepts attribute min_length that can set to 1 to require at least one value

**Comment by datakurre** [comment]
and yes, the field should also be required

**Comment by Shriyanshagro** [comment]
@datakurre min_length is not required here. Attribute `required` itself suffice the requirement.
