### ISSUE TITLE
Fix help text

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#70]
The help text for the content types field on Content Trigger and User Trigger says:
> Select certain content types which should be restricted to this event

It should say
> Select the content types to restrict this event to

Similarly the workflow transitions field on Content Trigger and Event Trigger says:
> Select certain workflow transitions which should be restricted to this event

It should say
> Select the workflow transitions to restrict this event to

**Comment by skleinfeldt** [comment]
Nitpick:
> Give the name of IFTTT event which you want to trigger

Should be:
> Give the name of the IFTTT event which you want to trigger

**Comment by datakurre** [comment]
I lost the issue on event name validation, but constraints is the easiest way to do that https://docs.plone.org/develop/addons/schema-driven-forms/customising-form-behaviour/validation.html
