### ISSUE TITLE
IFTTT event name help text

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#71]
The IFTTT event names are going to be sent as part of the webhook request URL, so they need to be URL friendly - no whitespace, all lower case. This needs to be part of the help text on the "IFTTT event name" field on all 5 forms (the 3 triggers, the easyform adapter, and the content rule action).
> Give the name of the IFTTT event which you want to trigger. This will be part of the webhook URL so should not contain white space or special characters - for example mysite_modified.

@Shriyanshagro @datakurre I think this ticket is important and should be fixed, and a version 1.1 release made. If some of the other easy tickets could be fixed along with it that would be great too. Maybe put all the changes in a bugfix PR?

**Comment by datakurre** [comment]
* [ ] update descriptions for event name fields
* [ ] add validators (or schema constraints) for those fields

Bugfix release 1.0.1 would be enough.

**Comment by skleinfeldt** [comment]
@Shriyanshagro please not that I am more interested in fixing the help text than in creating a solid validator, which might be hard. Having it be a single word wouldn't be enough, you'd need something like a lex rule to make sure there are no illegal characters.

**Comment by Shriyanshagro** [comment]
@skleinfeldt don't worry both of those requirements have been accomplished 💯
