### ISSUE TITLE
But does it work?

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#72]
I have been through all the docs and tested everything aside from manually making a content rule with an IFTTT action. I made some tickets for fine points but other than that everything worked as expected. Hurrah!!

However now I am doing the final step, which is to actually create an IFTTT applet to use one of the IFTTT triggers - and it isn't working for me. This could well be due to errors on my part, but I'm pretty stumped. @Shriyanshagro I think you should take a look. 

I have configured my secret key. I have created 3 triggers, one of each type (2 on site root and 1 on /news) and a form, also at site root. I am trying to use my IFTTT User Trigger in an applet that posts to the ifttt Slack channel when any object is modified. It is at the site root, called Site_Trigger_collective.ifttt_edits. The following details how I created the applet:

  Go to My Applets (upper left)
  Click New Applet
  Click +this
  Search for Webhooks and select it
  On Choose trigger screen click on Receive a web request
  Enter the Event Name: collective.ifttt_edits
  Click +that
  Action service - search for and choose Slack
  Connect to Slack
  In the popup select the Plone workspace
  Click Authorize (it magically authorized)
  Chose action: click Post to channel
  On the form
  - select Private Groups and ifttt
  - message: The "{{EventName}}" event occurred on the IFTTT Maker service: {{Value3}} modified "{{Value1}}" at {{Value2}} on the GSoC IFTTT Plone site.
  - title: The event named "{{EventName}}" occurred on the Maker Webhooks service
  - URL: blank
  - click Create action

  Review and finish - left receive notifications on

@Shriyanshagro can you see anything wrong with that? Did you ever create an applet that worked? Feel free to re-configure the site to use your secret key so you can try it out.

I will try a different trigger/event and a different applet action and I'll let you know what happens

**Comment by skleinfeldt** [comment]
Here's a screenshot of the top half of the Slack Post to Channel form described above:

![screen shot 2018-08-09 at 5 54 41 pm](https://user-images.githubusercontent.com/1198463/43930216-3567d2b8-9c06-11e8-9a16-2b3e2f0f625a.png)

**Comment by skleinfeldt** [comment]
PS When I magically authenticated with Slack I got this email. One possibility is that this install didn't work because I don't have permission.

Hi Sally,

You just installed IFTTT for the Plone Slack workspace.

If you didn't make this change (or if you've changed your mind), you can remove this app from your workspace by visiting the IFTTT configuration page.

If you have any questions, we're happy to help. Please reach out to us at feedback@slack.com.

Cheers,
- The team at Slack

**Comment by Shriyanshagro** [comment]
Hey, @skleinfeldt, you have taken the right steps to trigger ifttt.
Also, I believe you have already pointed out the error by yourself in one of the other open issues, that event name cannot contain space or dots(.)

Try out the same steps again with restricted event_name (maybe collevtive_ifttt_edits)

Thanks for letting us know of this issue and I regret to test this on my own at the first place.

**Comment by Shriyanshagro** [comment]
@datakurre while testing this feature I figured out that we were not using the required naming convention for keys of payloads.
Nevertheless, I will open a ticket for it

**Comment by skleinfeldt** [comment]
@Shriyanshagro this is not the reason for the failure. I renamed all 4 of my triggers before proceeding with this test, as you can see if you look on the content rules UI.

**Comment by Shriyanshagro** [comment]
@skleinfeldt can you try it again. As it's working for me and visible on slack itself.

**Comment by skleinfeldt** [comment]
w00t w00t!
