### ISSUE TITLE
Missing documentation section

### ISSUE THREAD

**Issue by skleinfeldt** [collective/collective.ifttt#73]
I just realized today that we are missing documentation on how to create IFTTT applets from the triggers that collective.ifttt creates. And it is not that easy to figure out how to do it! So I think adding a new section that covers this is important. The thing that is not obvious is that when you create your applet and click on +this, you need to search for and select the Webhooks service that you signed up for. See #72 for a complete run down of creating an applet.

**Comment by Shriyanshagro** [comment]
@skleinfeldt On a second thought, I don't see the need for this document, as we are not guiding anything new to the user.
I believe this document would serve nothing new to user, then what [this](https://collectiveifttt.readthedocs.io/en/latest/Using_Plone_RSS_Feeds_in_IFTTT_Applets.html) is serving. Moreover, a generalised guide to create IFTTT applets is also covered in the external link of [this ](https://collectiveifttt.readthedocs.io/en/latest/Introduction_to_IFTTT_Applets.html#what-is-an-applet) page.
So, I ask you to kindly think again.
