### ISSUE TITLE
event start time throws error

### ISSUE THREAD

**Issue by Shriyanshagro** [collective/collective.ifttt#77]
Execution of the following line throws Typeerror
https://github.com/collective/collective.ifttt/blob/b132f24667e6157d3887ee24539a70641471dd15/src/collective/ifttt/actions/ifttt.py#L132

error: `
                *** TypeError: ('Could not adapt', <Folder at /Plone/news>,
                 <InterfaceClass plone.event.interfaces.IEventAccessor>)
`

**Comment by datakurre** [comment]
Our issue as that we should have been using `self.event.object` instead of `self.context`.
